name: Playwright Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests and Generate HTML Report
        run: npx playwright test --reporter=html

      - name: Copy HTML report to root for Vercel
        run: |
          rm -rf playwright-report-old
          mv playwright-report playwright-report-old
          cp -r playwright-report-old/* ./  # copia para raiz do projeto

      - name: Upload artifact (opcional)
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ./playwright-report
