name: Run Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Instalar browsers do Playwright (com dependências)
        uses: microsoft/playwright-github-action@v1

      - name: Rodar testes
        run: npm run test:report

      - name: Fazer upload do relatório HTML
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
