name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-jammy

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes
        run: npx playwright test

      - name: Gerar relatório para deploy
        run: npm run build:report

      - name: Salvar relatório como artefato
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: report
